apiVersion: v1
kind: Service
metadata:
  name: axion-backend-service
  namespace: preprodns

spec:
  type: ClusterIP
  selector:
    app: axion-backend

  ports:
    - port: 8000
      targetPort: 8000